version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'tictactoe'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'

volumes:
  mysql:
    driver: local