services:
  line-webhook:
    container_name: line-webhook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - '.:/app/line-webhook'
    depends_on:
      - mysql
    networks:
      - spring-boot

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'tictactoe'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - spring-boot

volumes:
  mysql:
    driver: local

networks:
  spring-boot:
    driver: bridge
